name: "chain: smoke test"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      sha:
        type: string
        required: true

permissions:
  contents: read

jobs:
  smoke:
    runs-on: cronos
    steps:
      - run: echo "smoke testing ${{ inputs.environment }} at ${{ inputs.sha }}"; sleep 10
